development:
  adapter: mysql2
  database: issue_tracker_development
  username: root
  password: ""

test:
  adapter: mysql2
  database: issue_tracker_test
  username: root
  password: ""

production:
  adapter: mysql2
  database: issue_tracker_production
  username: root
  password: ""
